arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
preferred-supported-locales: [en, bn, ur, ar]
use-deferred-loading: false
synthetic-package: false
untranslated-messages-file: untranslated.txt
